# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSystemtestupload():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_systemtestupload(self):
    self.driver.get("http://127.0.0.1:5000/home")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.LINK_TEXT, "Visualize").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-btn").click()
    self.driver.find_element(By.LINK_TEXT, "League of Legends").click()
    self.driver.find_element(By.ID, "game_id").click()
    self.driver.find_element(By.ID, "game_id").click()
    self.driver.find_element(By.ID, "game_id").send_keys("111")
    self.driver.find_element(By.ID, "date_played").click()
    self.driver.find_element(By.ID, "date_played").send_keys("2002-12-12")
    self.driver.find_element(By.ID, "game_duration").click()
    self.driver.find_element(By.ID, "game_duration").send_keys("01:33:34")
    self.driver.find_element(By.ID, "winning_team").click()
    self.driver.find_element(By.ID, "winning_team").send_keys("red")
    self.driver.find_element(By.ID, "league_username").click()
    self.driver.find_element(By.ID, "league_username").send_keys("zed")
    self.driver.find_element(By.ID, "champion").click()
    self.driver.find_element(By.ID, "league_username").click()
    self.driver.find_element(By.ID, "league_username").send_keys("linshan")
    self.driver.find_element(By.ID, "champion").click()
    self.driver.find_element(By.ID, "champion").send_keys("yasuo")
    self.driver.find_element(By.ID, "kills").click()
    self.driver.find_element(By.ID, "kills").send_keys("22")
    self.driver.find_element(By.ID, "deaths").click()
    self.driver.find_element(By.ID, "deaths").send_keys("20")
    self.driver.find_element(By.ID, "assists").click()
    self.driver.find_element(By.ID, "assists").send_keys("40")
    self.driver.find_element(By.ID, "team").click()
    self.driver.find_element(By.ID, "team").send_keys("red")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Visualize").click()
  
