# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSystemtestsharing():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_systemtestsharing(self):
    self.driver.get("http://127.0.0.1:5000/home")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.LINK_TEXT, "reece").click()
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Account Settings").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Visualize").click()
    self.driver.find_element(By.LINK_TEXT, "Visualize").click()
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.LINK_TEXT, "reece").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Account Settings").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("ree")
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > button").click()
    assert self.driver.switch_to.alert.text == "You are already friends!"
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("bonnie")
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > button").click()
    assert self.driver.switch_to.alert.text == "You are already friends!"
  
