"""Add profile_pic to User model

Revision ID: 08a181bb9b7c
Revises: ef2ffce4f51f
Create Date: 2025-05-16 13:52:08.249222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a181bb9b7c'
down_revision = 'ef2ffce4f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friend_request', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_friend_request', ['sender_id', 'receiver_id'])

    # ### end Alembic commands ###
