"""replace old models with LeagueGame

Revision ID: 4327b8f955c6
Revises: c06b41a73a9c
Create Date: 2025-05-13 13:15:42.320278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4327b8f955c6'
down_revision = 'c06b41a73a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.DateTime(), nullable=False),
    sa.Column('game_duration', sa.String(length=20), nullable=False),
    sa.Column('winning_team', sa.String(length=150), nullable=False),
    sa.Column('league_username', sa.String(length=150), nullable=False),
    sa.Column('champion', sa.String(length=150), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('league_game_instance')
    op.drop_table('league_game_player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_game_player',
    sa.Column('league_username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('champion', sa.VARCHAR(length=150), nullable=False),
    sa.Column('kills', sa.INTEGER(), nullable=False),
    sa.Column('deaths', sa.INTEGER(), nullable=False),
    sa.Column('assists', sa.INTEGER(), nullable=False),
    sa.Column('kda', sa.FLOAT(), nullable=False),
    sa.Column('team', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['league_game_instance.game_id'], ),
    sa.ForeignKeyConstraint(['league_username'], ['user.league_username'], ),
    sa.PrimaryKeyConstraint('league_username', 'game_id')
    )
    op.create_table('league_game_instance',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('date_played', sa.DATETIME(), nullable=False),
    sa.Column('game_duration', sa.TIME(), nullable=False),
    sa.Column('winning_team', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.drop_table('league_game')
    # ### end Alembic commands ###
