"""empty message

Revision ID: 8573b22d70dc
Revises: 
Create Date: 2025-05-02 07:36:02.535862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8573b22d70dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_game_instance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.DateTime(), nullable=False),
    sa.Column('game_duration', sa.Time(), nullable=False),
    sa.Column('winning_team', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('league_username', sa.String(length=150), nullable=True),
    sa.Column('valorant_username', sa.String(length=150), nullable=True),
    sa.Column('PUBG_username', sa.String(length=150), nullable=True),
    sa.Column('apex_username', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PUBG_username'),
    sa.UniqueConstraint('apex_username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('league_username'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('valorant_username')
    )
    op.create_table('league_game_player',
    sa.Column('league_username', sa.String(length=150), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(length=150), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('team', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['league_game_instance.game_id'], ),
    sa.ForeignKeyConstraint(['league_username'], ['user.league_username'], ),
    sa.PrimaryKeyConstraint('league_username', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_game_player')
    op.drop_table('user')
    op.drop_table('league_game_instance')
    # ### end Alembic commands ###
