"""Add profile image

Revision ID: 9010eca63fcb
Revises: ef2ffce4f51f
Create Date: 2025-05-16 15:28:26.519495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9010eca63fcb'
down_revision = 'ef2ffce4f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friend_request', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_friend_request', ['sender_id', 'receiver_id'])

    # ### end Alembic commands ###
